apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: funnelai
  namespace: funnelai-dev
spec:
  interval: 1m0s
  ref:
    branch: dev
  secretRef:
    name: flux-system
    namespace: flux-system
  url: ssh://git@github.com/jdmchone/funnelAI
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: funnelai
  namespace: funnelai-dev
spec:
  interval: 10m0s
  path: ./dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: funnelai